function one() {
  window.alert(
    "The statue of Christ the Redeemer has become a symbolic protector of people. Like Jesus Christ, the statue protects the urban environment, like a roof over your head. Cristo Redentor is as important as any shelter. Christ the Redeemer provides protection for the soul."
  );
}
function two() {
  window.alert(
    "An immense mausoleum of white marble, built in Agra between 1631 and 1648 by order of the Mughal emperor Shah Jahan in memory of his favourite wife, the Taj Mahal is the jewel of Muslim art in India and one of the universally admired masterpieces of the world's heritage."
  );
}
function three() {
  window.alert(
    "The Colosseum was built as part of an imperial effort to revitalize Rome after the tumultuous year of the four emperors, 69 CE. As with other amphitheatres, the emperor Vespasian intended the Colosseum to be an entertainment venue, hosting gladiator fights, animal hunts, and even mock naval battles."
  );
}
function four() {
  window.alert(
    "The stepped pyramids, temples, columned arcades, and other stone structures of Chichén Itzá were sacred to the Maya and a sophisticated urban center of their empire from A.D. 750 to 1200"
  );
}
function five() {
  window.alert(
    "More than 7,000 feet above sea level in the Andes Mountains, Machu Picchu is the most visited tourist destination in Peru. A symbol of the Incan Empire and built around 1450AD, Machu Picchu was designated a UNESCO World Heritage Site in 1983 and was named one of the New Seven Wonders of the World in 2007."
  );
}
function six() {
  window.alert(
    "Famous for its rock-cut architecture and water conduit system, Petra is also called the Rose City because of the colour of the stone from which it is carved. It has been a UNESCO World Heritage Site since 1985. ... Petra is a symbol of Jordan, as well as Jordan's most-visited tourist attraction."
  );
}
function seven() {
  window.alert(
    "The first went up some four centuries before Qin Shi Huang, who became China's first emperor in 221 BC, ordered a decade-long project to unite and expand these defences into a single barrier. Construction to create the current 13,000 miles of wall continued, on and off, for more than two millennia."
  );
}  
